# Generated by Django 4.0.3 on 2022-03-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_clientemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemail',
            name='answered',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
