# Generated by Django 4.0.3 on 2022-03-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_phone_number2_alter_phone_name_alter_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepliedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=200)),
                ('pkey', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
