# Generated by Django 4.0.3 on 2022-03-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_repliedemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalMail', models.IntegerField(blank=True, default=0, null=True)),
                ('repliedMail', models.IntegerField(blank=True, default=0, null=True)),
                ('unrepliedMail', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
