# Generated by Django 4.0.3 on 2022-03-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_homevideo_text_remove_homevideo_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
    ]
