# Generated by Django 4.0.3 on 2022-04-10 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_testimonial_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientemail',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='clientemail',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientemail',
            name='answered',
            field=models.CharField(default='False', max_length=10, null=True),
        ),
    ]
